---

- name: "BeeGFS RPM key"
  rpm_key: state=present key=http://www.fhgfs.com/release/latest-stable/gpg/RPM-GPG-KEY-fhgfs

- name: "BeeGFS repository configuration"
  copy: src=fhgfs-rhel7.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: "Data directory"
  file: path=/data state=directory

- name: "Packages"
  yum: name="{{ item }}" state=present
  with_items:
  - augeas
  - fhgfs-utils
