---

- name: "BeeGFS RPM key"
  rpm_key: state=present key=http://www.beegfs.com/release/beegfs_2015.03/gpg/RPM-GPG-KEY-beegfs

- name: "BeeGFS repository configuration"
  copy: src=beegfs-rhel7.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: "Data directory"
  file: path=/data state=directory

- name: "Disable SELinux"
  selinux: state=disabled

- name: "Packages"
  yum: name="{{ item }}" state=latest
  with_items:
  - augeas
  - beegfs-utils
  - ntp

- name: "Ensure ntpd service is enabled and running"
  service: name=ntpd enabled=yes state=started

- name: "Enable ntpdate service is enabled and running"
  service: name=ntpdate enabled=yes state=started
